# k8s/cloudsql-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-secrets
type: Opaque
stringData:
  db_user: noter
  db_password: VerySecure123!        # Replace with your real password
  db_name: notedb
  db_host: 34.150.76.170  #was 10.105.181.3   # 👈 Use the **private IP of your Cloud SQL**
